cache: yarn
language: node_js
node_js:
  - '8'
os: linux
stages:
  - test
  - name: deploy
    if: (branch = "master") AND type != pull_request AND tag IS blank
jobs:
  include:
    - stage: deploy
      script:
        - yarn run travis-ssh
        - 'git remote set-url origin git@github.com:nativecode-dev/chest.git'
        - git checkout $TRAVIS_BRANCH
        - 'npm set //registry.npmjs.org/:_authToken "$NPM_TOKEN"'
        - yarn run travis-release
after_failure:
  - ls -lah --color=auto
after_success:
  - yarn run travis-coveralls
before_install:
  - 'curl -o- -L https://yarnpkg.com/install.sh | bash -s'
  - 'export PATH="$HOME/.yarn/bin:$PATH"'
