cache:
  directories:
    - node_modules
  yarn: true
language: node_js
node_js:
  - 'node'
os:
  - linux
  - osx
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm whoami
  - yarn run configure
stages:
  - test
  - name: coverage
    if: (branch = "master" OR branch = "develop") AND type != pull_request
  - name: release
    if: branch = "master" AND type != pull_request
jobs:
  include:
    - stage: coverage
      node_js: '8'
      os: linux
      script:
        - yarn run coveralls
    - stage: release
      node_js: '8'
      os: linux
      script:
        - yarn run setup ssh
        - git remote set-url origin git@github.com:nativecode-dev/chest.git
        - git checkout $TRAVIS_BRANCH
        - yarn run release
